#!/usr/bin/env python3
r"""ResetCalibrationTestState.py - Reset calibration test state

Purpose:
    While testing session calibration in the GUI, it is useful to revert the DB/filesystem
    back to a pre-calibration state.

This command will:
  1) Delete calibrated output FITS files generated by AstroFiler calibration
     (identified by having fitsFileOriginalFile set OR a filename starting with "cal_").
     - Deletes the file on disk (if present)
     - Deletes the corresponding fitsFile row in the database
  2) Set fitsFileSoftDelete = False for ALL remaining fitsFile rows
  3) Reset fitsFileCalibrated = 0 (and clear fitsFileCalibrationDate) for remaining LIGHT rows

Usage:
    .\\.venv\\Scripts\\python .\\commands\\ResetCalibrationTestState.py

Notes:
    - This is intended for testing. It will remove any file that starts with "cal_".
"""

import os
import sys
import argparse
import logging

# Configure Python path for new package structure - must be before any astrofiler imports
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src_path = os.path.join(project_root, 'src')

# Ensure src path is first in path to avoid conflicts with root astrofiler.py
if src_path in sys.path:
    sys.path.remove(src_path)
sys.path.insert(0, src_path)

from astrofiler.database import setup_database
from astrofiler.models import fitsFile as FitsFileModel
from astrofiler.exceptions import DatabaseError


def setup_logging(verbose: bool) -> logging.Logger:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler('astrofiler.log', mode='a'),
            logging.StreamHandler(sys.stdout)
        ]
    )
    return logging.getLogger(__name__)


def _is_generated_calibrated_output(row: FitsFileModel) -> bool:
    """Heuristic for calibrated outputs produced by AstroFiler."""
    original = getattr(row, 'fitsFileOriginalFile', None)
    if original is not None and str(original).strip():
        return True

    filename = getattr(row, 'fitsFileName', None)
    if not filename:
        return False

    base = os.path.basename(str(filename).replace('\\', os.sep).replace('/', os.sep))
    if base.lower().startswith('cal_'):
        return True

    return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Reset calibration test state (soft-deletes + generated cal_ outputs)")
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose logging')
    args = parser.parse_args()

    logger = setup_logging(args.verbose)

    try:
        if not setup_database():
            raise DatabaseError("Failed to setup database")

        # 1) Identify calibrated outputs to remove
        candidates = list(FitsFileModel.select())
        to_delete = [row for row in candidates if _is_generated_calibrated_output(row)]

        deleted_db_rows = 0
        deleted_files = 0
        missing_files = 0
        file_delete_errors = 0

        for row in to_delete:
            path = row.fitsFileName
            if path:
                try:
                    if os.path.exists(path):
                        os.remove(path)
                        deleted_files += 1
                    else:
                        missing_files += 1
                except Exception as e:
                    file_delete_errors += 1
                    logger.warning(f"Failed to delete file: {path} ({e})")

            # Delete DB row regardless of file deletion outcome
            try:
                row.delete_instance()
                deleted_db_rows += 1
            except Exception as e:
                logger.error(f"Failed to delete DB row for {path}: {e}")

        # 2) Reset soft-delete flags
        updated_softdelete = FitsFileModel.update(fitsFileSoftDelete=False).execute()

        # 3) Reset calibrated flags for remaining LIGHT files
        updated_calibrated = FitsFileModel.update(
            fitsFileCalibrated=0,
            fitsFileCalibrationDate=None
        ).where(
            (FitsFileModel.fitsFileType.in_(['LIGHT', 'LIGHT FRAME'])) &
            (FitsFileModel.fitsFileOriginalFile.is_null(True))
        ).execute()

        logger.info("Reset calibration test state complete")
        logger.info(f"Deleted calibrated output DB rows: {deleted_db_rows}")
        logger.info(f"Deleted calibrated output files: {deleted_files} (missing: {missing_files}, errors: {file_delete_errors})")
        logger.info(f"Reset fitsFileSoftDelete on rows: {updated_softdelete}")
        logger.info(f"Reset fitsFileCalibrated on LIGHT rows: {updated_calibrated}")

        print("\nReset complete.")
        print(f"- Deleted calibrated output DB rows: {deleted_db_rows}")
        print(f"- Deleted calibrated output files: {deleted_files} (missing: {missing_files}, errors: {file_delete_errors})")
        print(f"- Reset fitsFileSoftDelete on rows: {updated_softdelete}")
        print(f"- Reset fitsFileCalibrated on LIGHT rows: {updated_calibrated}\n")

        return 0

    except DatabaseError as e:
        print(f"\n{'='*70}")
        print("DATABASE ERROR")
        print(f"{'='*70}")
        print(f"\n{e}\n")
        print(f"{'='*70}\n")
        return 1
    except KeyboardInterrupt:
        print("\nOperation cancelled by user")
        return 1
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        print(f"\nError: {e}")
        print("Use -v/--verbose for details")
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
